[project]
name = "webcrawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "bs4>=0.0.2",
    "colorama>=0.4.6",
    "pymongo>=4.15.1",
]
